import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";

function createData(genericName, brandName, strength, dosing, cost, coverage) {
  return { genericName, brandName, strength, dosing, cost, coverage };
}

const rows = [
  createData(
    "Sumatriptan",
    "Imitrex",
    "100 mg",
    "PRN",
    "$35",
    "BC - SA / EIA - Covered"
  ),
  createData(
    "Sumatriptan",
    "Imitrex",
    "100 mg",
    "PRN",
    "$35",
    "BC - SA / EIA - Covered"
  ),
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main className={styles.main}>
        <TableContainer component={Paper}>
          <Table sx={{ minWidth: 650 }} aria-label="simple table">
            <TableHead>
              <TableRow>
                <TableCell>Generic Name</TableCell>
                <TableCell align="left">Brand Name</TableCell>
                <TableCell align="left">Strength</TableCell>
                <TableCell align="left">Dosing</TableCell>
                <TableCell align="left">90 Day Cost</TableCell>
                <TableCell align="left">Coverage</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {rows.map((row) => (
                <TableRow
                  key={row.genericName}
                  sx={{ "&:last-child td, &:last-child th": { border: 0 } }}
                >
                  <TableCell component="th" scope="row">
                    {row.genericName}
                  </TableCell>
                  <TableCell align="left">{row.brandName}</TableCell>
                  <TableCell align="left">{row.strength}</TableCell>
                  <TableCell align="left">{row.dosing}</TableCell>
                  <TableCell align="left">{row.cost}</TableCell>
                  <TableCell align="left">{row.coverage}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </main>
    </div>
  );
}
